hats-finance/hats-contracts

- contracts/HATTimelockController.sol
- test/hattimelockcontroller.js
Add timelock controller for hat vaults
> Add Hat timelock controller

- .coveralls.yml
- .github/workflows/pipeline.yml
- .gitignore
- .travis.yml
- package.json
> coverall fix

- contracts/HATMaster.sol
- contracts/HATVaults.sol
- test/hatvaults.js
> Disallow changing reward multipliers las value

- contracts/HATMaster.sol
- contracts/HATVaults.sol
- test/hatvaults.js
- test/tokenlock.js
> Allow multiple pools with the same token

- contracts/HATVaults.sol
- contracts/mocks/ERC20Mock.sol
- test/hatvaults.js
> Reset approval of token after

- contracts/tokenlock/TokenLock.sol
- test/tokenlock.js
> Add sweep token to token lock

- contracts/HATMaster.sol
- test/hattimelockcontroller.js
- test/hatvaults.js
> Remove minting of reward

- contracts/HATMaster.sol
- contracts/HATVaults.sol
- contracts/tokenlock/TokenLock.sol
- test/hattimelockcontroller.js
- test/hatvaults.js
- test/tokenlock.js
Fix #101
For now, the default fee for a pool is 0, and it does not apply for emergency withdrawal (specs are unclear about those).
> Add withdrawal fee

- contracts/HATVaults.sol
- test/hatvaults.js
Fix #110
Adds CommitteeCheckedIn, SetRewardMultipliers, and SetClaimFee events
> Add missing events

- contracts/vaults/Base.sol
- contracts/vaults/Deposit.sol
- test/hatvaults.js
Fix #226 (still need to do same for withdrawal)
> Fix #226 (MINIMUM_DEPOSIT)

- contracts/HATTimelockController.sol
- contracts/HATVaults.sol
- contracts/RewardController.sol
- contracts/interfaces/IRewardController.sol
- contracts/mocks/PoolsManagerMock.sol
- contracts/vaults/Base.sol
- contracts/vaults/Deposit.sol
- contracts/vaults/Getters.sol
- contracts/vaults/Params.sol
- contracts/vaults/Pool.sol
- contracts/vaults/Withdraw.sol
- package-lock.json
- scripts/hatvaultsdeploy.js
- test/arbitrator.js
- test/common.js
- test/hattimelockcontroller.js
- test/hatvaults.js
Moves the whole reward logic to the reward controller.
Fix #228 (still need to write a test for that case)
> Move reward logic to reward controller

- contracts/HATTimelockController.sol
- contracts/HATVaultsRegistry.sol
- test/hattimelockcontroller.js
- test/hatvaults.js
Swap multiple beneficiaries in a single swapBurnSend call.
> Swap multiple beneficiaries

- contracts/HATTimelockController.sol
- contracts/HATVaultsRegistry.sol
- contracts/mocks/UniSwapV3RouterMock.sol
- contracts/vaults/Base.sol
- contracts/vaults/Claim.sol
- docs/roles.md
- test/common.js
- test/hattimelockcontroller.js
- test/hatvaults.js
- Remove burn of swapped tokens
- Update amounts used correctly when router only swaps partial amount ( Fix #278 )
> Swap burn send updates

- contracts/HATVaultsRegistry.sol
- docs/roles.md
- scripts/hatvaultsdeploy.js
- test/common.js
- test/hattimelockcontroller.js
- test/hatvaults.js
> Remove whitlisting of routers

- contracts/HATVaultsRegistry.sol
- test/hattimelockcontroller.js
- test/hatvaults.js
> Save vault visibility

- contracts/HATTimelockController.sol
- contracts/HATVault.sol
- contracts/HATVaultsRegistry.sol
- contracts/mocks/PoolsManagerMock.sol
- contracts/vaults/Base.sol
- contracts/vaults/Claim.sol
- contracts/vaults/Params.sol
- docs/parameters.md
- docs/roles.md
- scripts/hatvaultsdeploy.js
- test/arbitrator.js
- test/common.js
- test/hattimelockcontroller.js
- test/hatvaults.js
> Make vaults ownable individualy

- contracts/HATVault.sol
- contracts/vaults/Base.sol
- contracts/vaults/Deposits.sol
- contracts/vaults/Withdrawals.sol
- test/hatvaults.js
Allow transfer and deposit to user with expired withdraw request
> Allow deposit to user with expired withdraw request

- contracts/HATVault.sol
- contracts/HATVaultsRegistry.sol
- contracts/vaults/Base.sol
- contracts/vaults/Claim.sol
- test/hatvaults.js
> Add emergency pause

- contracts/HATVault.sol
- test/arbitrator.js
> Add claim expiry logic

- contracts/HATVault.sol
- docs/parameters.md
- test/hatvaults.js
> Max committee bounty at 10%

- contracts/HATVault.sol
- contracts/HATVaultsRegistry.sol
- contracts/interfaces/IHATVault.sol
- test/hatvaults.js
Emit SetVaultDescription on initialize and add a test for the create vault event
> Emit SetVaultDescription on initialize

- contracts/HATTimelockController.sol
- test/hattimelockcontroller.js
> Add emergency pause to timelock whitelist

- contracts/HATGovernanceArbitrator.sol
- contracts/HATTimelockController.sol
- contracts/HATVault.sol
- contracts/HATVaultsRegistry.sol
- package-lock.json
- scripts/hatvaultsdeploy.js
- test/common.js
- test/hattimelockcontroller.js
- test/hatvaults.js
> Add arbitrator contract

- docs/parameters.md
vaultDescription was updated be modifiable by registry owner
> update parameters doc to reflect the changes 

- contracts/HATTimelockController.sol
- contracts/HATVault.sol
- contracts/RewardController.sol
- contracts/interfaces/IHATVault.sol
- docs/dodoc/HATTimelockController.md
- docs/dodoc/HATToken.md
- docs/dodoc/HATVault.md
- docs/dodoc/HATVaultsRegistry.md
- docs/dodoc/interfaces/IHATToken.md
- docs/dodoc/interfaces/IHATVault.md
- docs/dodoc/interfaces/IHATVaultsRegistry.md
- docs/dodoc/mocks/HATTokenMock.md
- docs/dodoc/tokenlock/TokenLock.md
- docs/parameters.md
- test/hattimelockcontroller.js
- test/hatvaults.js
Replace the setRewardController with addReward controller to have multiple reward controllers.
> Add reward controller

- contracts/HATVault.sol
- contracts/interfaces/IHATVault.sol
- docs/dodoc/HATVault.md
- docs/dodoc/interfaces/IHATVault.md
- test/hatvaults.js
Added slippage protected options of the withdrawAndClaim and the redeemAndClaim functions
> Add slippage protected withdraw/redeem with claim

- contracts/HATVault.sol
- contracts/interfaces/IHATVault.sol
- docs/dodoc/HATVault.md
- docs/dodoc/mocks/HATVaultV2Mock.md
- test/hatvaults.js
> Add VERSION property
